### ISSUE TITLE
Error: transaction failed precheck with status INVALID_SIGNATURE

### ISSUE THREAD

**Issue by bafu** [ed-marquez/hedera-hethers-example#2]
Redirected here from [this article](https://hedera.com/blog/how-to-use-hethers-js-to-deploy-smart-contracts-on-hedera), I tried to run the commands below but failed to run `index.js`

```
# After setting up .env

$ npm i
...

$ node index.js

- STEP 1 ===================================

- Alice's address: 0x0000000000000000000000000000000002bcc8f9

- Wallet address: 0x0000000000000000000000000000000002bc896f

- Wallet public key: 0x0446735cc52001ff66b687218a5ee8e18287ab0e582828b86b45473bda6afa5a62ce481ed130153d4380458416b75a7017c06f70f1188bca0dde11151fe4e737b9

- Wallet address balance: 10000.0 hbar

- STEP 2 ===================================
(node:18440) UnhandledPromiseRejectionWarning: Error: transaction 0.0.45910383@1654718914.808069996 failed precheck with status INVALID_SIGNATURE (code=INVALID_SIGNATURE, version=providers/1.1.1)
    at Logger.makeError (/home/bafu/codes/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/logger/lib/index.js:186:21)
    at DefaultHederaProvider.<anonymous> (/home/bafu/codes/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/providers/lib/base-provider.js:633:38)
    at step (/home/bafu/codes/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/providers/lib/base-provider.js:78:23)
    at Object.throw (/home/bafu/codes/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/providers/lib/base-provider.js:59:53)
    at rejected (/home/bafu/codes/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/providers/lib/base-provider.js:51:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ed-marquez** [comment]
I believe I've seen that issue when people use ED25519 keys instead of ECDSA keys. The article mentions: "At the time of this writing, Hethers.js only supports ECDSA private keys, thus the private key for the signer must be of that type. ED25519 keys will be supported soon."

If you're working with the account from the Hedera portal, that uses ED25519 keys. You will need to create an account that uses ECDSA keys. Please see the documentation for how to do that: https://docs.hedera.com/guides/docs/sdks/keys/generate-a-new-key-pair AND https://docs.hedera.com/guides/docs/sdks/cryptocurrency/create-an-account

**Comment by bafu** [comment]
Thanks for sharing the info. After migrating to the ECDSA private key, I got a new error:

```
$ node index.js

- STEP 1 ===================================

- Alice's address: 0x0000000000000000000000000000000002bcc8f9

- Wallet address: 0x0000000000000000000000000000000002bcde4c

- Wallet public key: 0x043a9d08c8ac997283e06650520215babf90da281dd8dad7428b8016e64975e89ff4e3b5cfc56e15e02ce8736fac80822c4cb818ce3b4e85c5c8c024d16078240c

- Wallet address balance: 10.00005 hbar

- STEP 2 ===================================

- Contract deployment status: 1

- Contract address: 0x0000000000000000000000000000000002bcdea0

- STEP 3 ===================================
(node:83947) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_code' of undefined
    at checkError (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:107:26)
    at Wallet.<anonymous> (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:260:47)
    at step (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:78:23)
    at Object.throw (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:59:53)
    at rejected (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:51:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:83947) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:83947) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by theiceeman** [comment]
Hi @ed-marquez , is this also an issue on hedera-js-sdk?
Because im experiencing a similar issue and cant seem to figure out why im getting the INVALID_SIGNATURE error.

**Comment by vishaloneto11** [comment]
i see the same issue

**Comment by VaibhavArora19** [comment]
Hey I am seeing the same issue while using hashgraph sdk. Also what if the account is not created from hedera portal, then how can we get our hands on the ECDSA private key

**Comment by ed-marquez** [comment]
Please follow part 1 in this tutorial to create an account with an ECDSA key that is also compatible iwth EVM tools: https://hedera.com/blog/how-to-deploy-smart-contracts-on-hedera-using-truffle

Here's the documentation reference: https://docs.hedera.com/hedera/core-concepts/accounts/auto-account-creation

I would suggest not using Hethers. Consider using standard EVM tools like Ethers JS, Web3 JS, HardHat, etc. 
Hethers is not being actively maintained anymore given the compatibility with standard tools like the ones mentioned above.

**Comment by VaibhavArora19** [comment]
Oh! can we interact with smart contracts deployed on hedera using ethers? If yes, then the read methods are free to call or do we have to pay some gas while using ethers as we do while using Hethers?
