### ISSUE TITLE
TypeError: Cannot read property '_code' of undefined

### ISSUE THREAD

**Issue by bafu** [ed-marquez/hedera-hethers-example#3]
Following the steps in [this article](https://hedera.com/blog/how-to-use-hethers-js-to-deploy-smart-contracts-on-hedera) and fixing the previous [`INVALID_SIGNATURE` issue](https://github.com/ed-marquez/hedera-hethers-example/issues/2), I got a new error:

```
$ node index.js

- STEP 1 ===================================

- Alice's address: 0x0000000000000000000000000000000002bcc8f9

- Wallet address: 0x0000000000000000000000000000000002bcde4c

- Wallet public key: 0x043a9d08c8ac997283e06650520215babf90da281dd8dad7428b8016e64975e89ff4e3b5cfc56e15e02ce8736fac80822c4cb818ce3b4e85c5c8c024d16078240c

- Wallet address balance: 10.00005 hbar

- STEP 2 ===================================

- Contract deployment status: 1

- Contract address: 0x0000000000000000000000000000000002bcdea0

- STEP 3 ===================================
(node:83947) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_code' of undefined
    at checkError (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:107:26)
    at Wallet.<anonymous> (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:260:47)
    at step (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:78:23)
    at Object.throw (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:59:53)
    at rejected (/home/bafu/codes/evm-survey/hedera-evm-survey/hedera-hethers-example/node_modules/@hethers/abstract-signer/lib/index.js:51:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:83947) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:83947) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bafu** [comment]
The difference between the [Codesandbox example](https://codesandbox.io/s/hedera-example-contract-hethers-js-j0ltgh?file=/index.js) and my working environment is

```
-    "@hashgraph/hethers": "1.1.0",
-    "@hashgraph/sdk": "2.11.3",
-    "dotenv": "14.2.0",
+    "@hashgraph/hethers": "^1.1.2",
+    "@hashgraph/sdk": "^2.15.0",
+    "dotenv": "^16.0.0"
```

I can run the Codesandbox example successfully

```
- STEP 1 ===================================

- Alice's address: 0x0000000000000000000000000000000002bcc8f9

- Wallet address: 0x0000000000000000000000000000000002bcde4c

- Wallet public key: 0x043a9d08c8ac997283e06650520215babf90da281dd8dad7428b8016e64975e89ff4e3b5cfc56e15e02ce8736fac80822c4cb818ce3b4e85c5c8c024d16078240c

- Wallet address balance: 82.69699686 hbar

- STEP 2 ===================================

- Contract deployment status: 1

- Contract address: 0x0000000000000000000000000000000002bcdf1c

- STEP 3 ===================================

- ERC20 token symbol: MyToken

- Transaction ID for ERC20 transfer: 0.0.45932108-1654792764-410315390

- Wallet ERC20 token (MyToken) balance: 75

- Alice's ERC20 token (MyToken) balance: 25

- DONE ===================================

- Event: 0x0000000000000000000000000000000002bCdE4C sent 25 tokens to 0x0000000000000000000000000000000002BcC8f9
```
